# Generated by Django 5.2 on 2025-12-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_techfest_participants_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('email', models.CharField()),
                ('phone', models.CharField()),
                ('password', models.CharField()),
                ('businessname', models.CharField()),
                ('city', models.CharField()),
                ('area', models.CharField()),
                ('services', models.JSONField(default=list)),
                ('preferences', models.JSONField(default=list)),
                ('date', models.CharField()),
            ],
        ),
    ]
