# Generated by Django 5.2 on 2025-12-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_location_personal_info_preferences_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='liability',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='tax',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='workman',
            field=models.CharField(null=True),
        ),
    ]
