# Generated by Django 5.2 on 2025-12-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_personal_info_liability_personal_info_tax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='liability',
            new_name='img_liability',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='tax',
            new_name='img_tax',
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='workman',
            new_name='img_workman',
        ),
    ]
