# Generated by Django 5.2 on 2025-12-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_liability_personal_info_img_liability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
