# Generated by Django 5.2 on 2025-12-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_personal_info_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='img',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='status',
            field=models.CharField(default='pending'),
        ),
    ]
